"""
Django settings for stashcast project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)

SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)

CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)

# Application definition

INSTALLED_APPS = [
    'unfold',  # Must be before django.contrib.admin
    'media',  # Must be before admin to override templates
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'bx_django_utils',
    'huey_monitor',
]

UNFOLD = {
    'SITE_TITLE': 'StashCast',
    'SITE_HEADER': 'StashCast',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': 'Tools',
                'items': [
                    {
                        'title': 'Add URL',
                        'link': '/admin/tools/add-url/',
                        'icon': 'add_link',
                    },
                    {
                        'title': 'Grid View',
                        'link': '/admin/tools/grid/',
                        'icon': 'grid_view',
                    },
                    {
                        'title': 'List View',
                        'link': '/admin/tools/list/',
                        'icon': 'view_list',
                    },
                    {
                        'title': 'Bookmarklet',
                        'link': '/admin/tools/bookmarklet/',
                        'icon': 'bookmark',
                    },
                    {
                        'title': 'Feed Links',
                        'link': '/admin/tools/feeds/',
                        'icon': 'rss_feed',
                    },
                    {
                        'title': 'About',
                        'link': '/admin/tools/preferences/',
                        'icon': 'info',
                    },
                    {
                        'title': 'Site Home',
                        'link': '/',
                        'icon': 'home',
                    },
                ],
            },
            {
                'title': 'Administration',
                'items': [
                    {
                        'title': 'Media Items',
                        'link': '/admin/media/mediaitem/',
                        'icon': 'play_circle',
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stashcast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'media.context_processors.stashcast_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'stashcast.wsgi.application'

STASHCAST_DATA_DIR = Path(os.environ.get('STASHCAST_DATA_DIR', BASE_DIR / 'data'))
STASHCAST_MEDIA_DIR = STASHCAST_DATA_DIR / 'media'


os.environ['NLTK_DATA'] = os.environ.get('NLTK_DATA', str(STASHCAST_DATA_DIR))

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': STASHCAST_DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Language code from environment variable (e.g., 'en', 'en-us', 'es', 'pl')
# This sets the UI language and the language for video subtitles/transcripts
LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'en-us')

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('pt', 'Português'),
    ('pl', 'Polski'),
]

# Path to translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True

# Extract the primary language code for yt-dlp subtitles (e.g., 'en' from 'en-us')
# This will be used to download subtitles/transcripts in the configured language
STASHCAST_SUBTITLE_LANGUAGE = LANGUAGE_CODE.split('-')[0]

# Download subtitles for video
STASHCAST_WRITE_SUBTITLES = env.bool('STASHCAST_WRITE_SUBTITLES', default=True)

# Download automation subtitles for video
STASHCAST_WRITE_AUTOMATION_SUBTITLES = env.bool('STASHCAST_WRITE_AUTOMATION_SUBTITLES', default=True)

# Validate that the configured language is supported
SUPPORTED_LANGUAGE_CODES = [code for code, name in LANGUAGES]
# Allow both primary codes (e.g., 'en') and regional variants (e.g., 'en-us')
PRIMARY_LANGUAGE = LANGUAGE_CODE.split('-')[0]
if (
    PRIMARY_LANGUAGE not in SUPPORTED_LANGUAGE_CODES
    and LANGUAGE_CODE not in SUPPORTED_LANGUAGE_CODES
):
    raise ValueError(
        f"Unsupported LANGUAGE_CODE: '{LANGUAGE_CODE}'. "
        f'Supported languages: {", ".join(SUPPORTED_LANGUAGE_CODES)}. '
        f'Set LANGUAGE_CODE environment variable to one of the supported languages.'
    )


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directory where collectstatic will collect static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STASHCAST Configuration

STASHCAST_USER_TOKEN = env('STASHCAST_USER_TOKEN')

# Require user token for RSS feeds (set to 'true' to enable)
REQUIRE_USER_TOKEN_FOR_FEEDS = (
    os.environ.get('REQUIRE_USER_TOKEN_FOR_FEEDS', 'false').lower() == 'true'
)

# Optional environment variables
STASHCAST_MEDIA_BASE_URL = os.environ.get('STASHCAST_MEDIA_BASE_URL', None)

# Default yt-dlp args optimized for mobile playback
# Audio: AAC codec in M4A container is widely supported
# Metadata is embedded directly into the media file
# Subtitles are converted to VTT format by yt-dlp
# Note: --embed-thumbnail removed because it deletes the thumbnail file after embedding.
# We need the thumbnail file for grid view and RSS feed artwork.
# Note: --convert-thumbnails removed due to yt-dlp race condition causing
# FileNotFoundError when FFmpeg tries to convert before file is ready.
# Thumbnails are converted to PNG in process_files() after download completes.
STASHCAST_DEFAULT_YTDLP_ARGS_AUDIO = os.environ.get(
    'STASHCAST_DEFAULT_YTDLP_ARGS_AUDIO',
    '--audio-format m4a --audio-quality 128K --embed-metadata --convert-subs vtt',
)

# Video: H.264/AAC in MP4 container for maximum mobile compatibility
# Limit to 720p to balance quality and file size
# Metadata is embedded, subtitles converted to VTT and embedded
# Note: --embed-thumbnail and --convert-thumbnails removed (see audio args comment above)
#
# The audio selector MUST pin AAC (ext=m4a). A bare "+ba" picks whatever YouTube
# considers best, which is nowadays Opus in a WebM stream - and Opus cannot be muxed
# into MP4, so yt-dlp silently falls back to an .mkv container. Apple Podcasts (and
# iOS generally) plays neither Matroska nor Opus, so such an episode fails with
# "Cannot play this episode on this device". Fallbacks below keep a download working
# when the ideal pair is unavailable, in decreasing order of client compatibility.
STASHCAST_CONVERT_SUBS = ''
if STASHCAST_WRITE_SUBTITLES or STASHCAST_WRITE_AUTOMATION_SUBTITLES:
    STASHCAST_CONVERT_SUBS = '--convert-subs vtt --embed-subs '

STASHCAST_DEFAULT_YTDLP_ARGS_VIDEO = os.environ.get(
    'STASHCAST_DEFAULT_YTDLP_ARGS_VIDEO',
    '--format "'
    # H.264 video + AAC audio: muxes into a real MP4 that every client plays
    'bv*[height<=720][vcodec^=avc1]+ba[ext=m4a]/'
    # A ready-made progressive MP4 (usually H.264 + AAC as well)
    'b[height<=720][ext=mp4]/'
    # Any video plus AAC audio - still an MP4 container
    'bv*[height<=720]+ba[ext=m4a]/'
    # Last resort: take what there is rather than failing the download
    'b[height<=720]'
    '" '
    '--merge-output-format mp4 '
    '--embed-metadata '
    + STASHCAST_CONVERT_SUBS
)

# Make sure a downloaded video can actually be played by podcast clients.
# When the download ends up in a container/codec combination Apple Podcasts and iOS
# reject (Matroska/WebM, AV1, VP9, Opus), it is repacked as MP4/H.264/AAC. Streams
# already in a supported codec are copied, so the usual cost is an audio re-encode.
# This is a safety net: pinning AAC in STASHCAST_DEFAULT_YTDLP_ARGS_VIDEO avoids it
# entirely and is much cheaper. Set to false to keep files exactly as downloaded.
STASHCAST_ENSURE_PLAYABLE_VIDEO = os.environ.get(
    'STASHCAST_ENSURE_PLAYABLE_VIDEO', 'true'
).lower() in ('true', '1', 'yes')

# FFmpeg args for transcoding (if needed)
STASHCAST_DEFAULT_FFMPEG_ARGS_AUDIO = os.environ.get(
    'STASHCAST_DEFAULT_FFMPEG_ARGS_AUDIO', '-c:a aac -b:a 128k'
)

STASHCAST_DEFAULT_FFMPEG_ARGS_VIDEO = os.environ.get(
    'STASHCAST_DEFAULT_FFMPEG_ARGS_VIDEO',
    '-c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart',
)

STASHCAST_SLUG_MAX_WORDS = int(os.environ.get('STASHCAST_SLUG_MAX_WORDS', '6'))
STASHCAST_SLUG_MAX_CHARS = int(os.environ.get('STASHCAST_SLUG_MAX_CHARS', '40'))
STASHCAST_SUMMARY_SENTENCES = int(os.environ.get('STASHCAST_SUMMARY_SENTENCES', '8'))

# Optional: Proxy URL for yt-dlp requests
# Use residential proxy to avoid YouTube blocking cloud VM IPs
# Formats: http://host:port, socks5://host:port, socks5://user:pass@host:port
# See docs/YOUTUBE_AUTH.md for setup instructions
STASHCAST_YTDLP_PROXY = os.environ.get('STASHCAST_YTDLP_PROXY', None)

# Optional: path to a Netscape-format cookies.txt file used for every yt-dlp call.
# Cookies from a logged-in session are the most reliable cure for "HTTP Error 403:
# Forbidden" and "Sign in to confirm you're not a bot" on YouTube.
# See docs/YOUTUBE_AUTH.md
STASHCAST_YTDLP_COOKIES_FILE = os.environ.get('STASHCAST_YTDLP_COOKIES_FILE', None)

# Optional: read cookies directly from a local browser profile instead of a file.
# Format: BROWSER[+KEYRING][:PROFILE][::CONTAINER], e.g. 'firefox' or 'chrome:Default'.
# Only works when the browser profile is reachable from the app (not in a container).
STASHCAST_YTDLP_COOKIES_FROM_BROWSER = os.environ.get(
    'STASHCAST_YTDLP_COOKIES_FROM_BROWSER', None
)

# YouTube player clients tried in order when a download fails with 403 Forbidden.
# The first entry 'default' means "whatever yt-dlp picks on its own"; the remaining
# ones are retried with an explicit --extractor-args youtube:player_client=...
# Set to a single value to disable the fallback chain.
STASHCAST_YTDLP_PLAYER_CLIENTS = os.environ.get(
    'STASHCAST_YTDLP_PLAYER_CLIENTS', 'default,tv,web_safari,mweb,tv_embedded'
)

# Optional: impersonate a browser TLS/HTTP fingerprint (requires curl_cffi).
# Useful when the media CDN rejects the plain python-requests fingerprint.
# Examples: 'chrome', 'safari', 'chrome-110'. Empty = disabled.
STASHCAST_YTDLP_IMPERSONATE = os.environ.get('STASHCAST_YTDLP_IMPERSONATE', None)

# Optional: JavaScript runtimes yt-dlp may use to solve YouTube player challenges.
# yt-dlp looks for 'deno' on PATH by default (the Docker image ships it), so this is
# only needed for bare-metal installs that have a different runtime available.
# Format: comma-separated NAME[:PATH], e.g. 'node' or 'node:/usr/local/bin/node'.
# Supported names: deno, node, bun, quickjs.
STASHCAST_YTDLP_JS_RUNTIMES = os.environ.get('STASHCAST_YTDLP_JS_RUNTIMES', None)

# Optional: random delay between yt-dlp requests, in seconds, to reduce the chance of
# YouTube's rate limiting / bot detection kicking in. 0 disables it.
# Use these instead of putting --sleep-interval in STASHCAST_DEFAULT_YTDLP_ARGS_*:
# those variables REPLACE the defaults wholesale, so adding a sleep flag there also
# silently drops the format selector and would break playback compatibility.
STASHCAST_YTDLP_SLEEP_INTERVAL = int(os.environ.get('STASHCAST_YTDLP_SLEEP_INTERVAL', '0'))
STASHCAST_YTDLP_MAX_SLEEP_INTERVAL = int(
    os.environ.get('STASHCAST_YTDLP_MAX_SLEEP_INTERVAL', '0')
)

# Retry counts for yt-dlp downloads (fragments of a DASH stream expire quickly,
# so a few retries turn a transient 403 into a successful download).
STASHCAST_YTDLP_RETRIES = int(os.environ.get('STASHCAST_YTDLP_RETRIES', '10'))
STASHCAST_YTDLP_FRAGMENT_RETRIES = int(os.environ.get('STASHCAST_YTDLP_FRAGMENT_RETRIES', '10'))
STASHCAST_YTDLP_EXTRACTOR_RETRIES = int(os.environ.get('STASHCAST_YTDLP_EXTRACTOR_RETRIES', '3'))

# Podcast Index API credentials (optional, for podcast RSS feed discovery)
# Get free API keys at: https://podcastindex.org/
PODCAST_INDEX_API_KEY = os.environ.get('PODCAST_INDEX_API_KEY', None)
PODCAST_INDEX_API_SECRET = os.environ.get('PODCAST_INDEX_API_SECRET', None)

# Spotify URL handling: auto-select first search result (no user input needed)
STASHCAST_ACCEPT_FIRST_MATCH = os.environ.get('STASHCAST_ACCEPT_FIRST_MATCH', '').lower() in (
    'true',
    '1',
    'yes',
)

# Optional: Maximum number of episodes (READY status) to keep
# When the limit is reached, new downloads are blocked until episodes are deleted
# 0 or unset = unlimited
STASHCAST_MAX_EPISODES = int(os.environ.get('STASHCAST_MAX_EPISODES', '0'))

# YouTube channel auto-sync
# Groups with a youtube_channel_url are periodically checked for new uploads,
# which are downloaded as audio into that group by the sync_youtube_channels task.
# Interval in hours between checks (clamped to 1..23). Default: every 3 hours.
STASHCAST_YOUTUBE_SYNC_HOURS = int(os.environ.get('STASHCAST_YOUTUBE_SYNC_HOURS', '3'))
# How many of the most recent uploads to consider per check. Bounds the first-run
# back-catalogue and keeps each check cheap. Default: 5.
STASHCAST_YOUTUBE_SYNC_MAX_VIDEOS = int(
    os.environ.get('STASHCAST_YOUTUBE_SYNC_MAX_VIDEOS', '5')
)

# --- Paced download queue -------------------------------------------------------
# Items found by the YouTube channel sync are not enqueued all at once (that floods
# the Huey workers). They are created with status QUEUED and released one batch per
# interval by the process_download_queue periodic task.

# How often the queue releases work, in minutes. Clamped to 1..59 so the '*/N'
# minute crontab expression stays valid.
STASHCAST_DOWNLOAD_QUEUE_MINUTES = int(os.environ.get('STASHCAST_DOWNLOAD_QUEUE_MINUTES', '5'))

# How many queued items to release per interval. Raise it to backfill a new channel
# faster; 1 keeps the load as low as possible.
STASHCAST_DOWNLOAD_QUEUE_BATCH = int(os.environ.get('STASHCAST_DOWNLOAD_QUEUE_BATCH', '1'))

# How many times a download may be attempted before the item is marked ERROR.
# 1 disables retrying.
STASHCAST_DOWNLOAD_MAX_ATTEMPTS = int(os.environ.get('STASHCAST_DOWNLOAD_MAX_ATTEMPTS', '3'))

# --- Speech to text (Wyoming / Whisper) ------------------------------------------
# Transcripts are produced by a Wyoming protocol server you run yourself, such as
# wyoming-whisper. Nothing is sent anywhere else. Podcast clients that support
# transcripts (Apple Podcasts among them) pick the result up from the RSS feed.
STASHCAST_WHISPER_ENABLED = os.environ.get('STASHCAST_WHISPER_ENABLED', '').lower() in (
    'true',
    '1',
    'yes',
)

# Address of the Wyoming server: 'tcp://host:port', 'host:port' or 'host' (port 10300).
STASHCAST_WHISPER_URI = os.environ.get('STASHCAST_WHISPER_URI', 'tcp://whisper:10300')

# Language of the audio, e.g. 'pl'. Empty means "let the model work it out", in which
# case the language heard in the first window is reused for the whole episode.
#
# Deliberately NOT defaulting to the site language: the language of the admin interface
# says nothing about the language people speak in the episodes. Defaulting to it told
# Whisper that Polish recordings were English, and the model answered with an English
# translation of what it heard - a transcript that starts in one language and continues
# in another. Set this explicitly whenever you know the language.
STASHCAST_WHISPER_LANGUAGE = os.environ.get('STASHCAST_WHISPER_LANGUAGE', '')

# Whisper returns one block of text with no timings, so audio is sent in windows of this
# many seconds and the window boundaries become the transcript's cue timings. Smaller
# windows give finer timings and shorter requests; larger ones give the model more
# surrounding context, which can help it at sentence boundaries. Anything below 5 is
# raised to 5 by the transcriber.
STASHCAST_WHISPER_WINDOW_SECONDS = int(
    os.environ.get('STASHCAST_WHISPER_WINDOW_SECONDS', '15')
)

# Socket timeout for a single window, in seconds.
STASHCAST_WHISPER_TIMEOUT_SECONDS = int(
    os.environ.get('STASHCAST_WHISPER_TIMEOUT_SECONDS', '300')
)

# How far a downloaded file's real duration may differ from the duration reported by
# the source before it is treated as incomplete. Containers round and encoders pad, so
# a second or two is normal; a bigger gap means the download was cut short.
# Used by ./manage.py check_durations and the "Duration" filter in the admin.
STASHCAST_DURATION_TOLERANCE_SECONDS = int(
    os.environ.get('STASHCAST_DURATION_TOLERANCE_SECONDS', '3')
)

# Retry pacing per error category (see media/service/errors.py).
# A premiere is retried around the time it airs rather than a few minutes later, and a
# bot check / rate limit is given a long rest instead of hammering YouTube.
STASHCAST_DOWNLOAD_RETRY_SCHEDULED_MINUTES = int(
    os.environ.get('STASHCAST_DOWNLOAD_RETRY_SCHEDULED_MINUTES', '60')
)
STASHCAST_DOWNLOAD_RETRY_BLOCKED_MINUTES = int(
    os.environ.get('STASHCAST_DOWNLOAD_RETRY_BLOCKED_MINUTES', '120')
)
# Premieres wait hours between attempts, so they get their own (larger) budget.
STASHCAST_DOWNLOAD_SCHEDULED_MAX_ATTEMPTS = int(
    os.environ.get('STASHCAST_DOWNLOAD_SCHEDULED_MAX_ATTEMPTS', '8')
)

# After this many minutes without an update, an item still sitting in PREFETCHING /
# DOWNLOADING / PROCESSING is treated as abandoned (worker died mid-task) and requeued.
STASHCAST_STUCK_TIMEOUT_MINUTES = int(os.environ.get('STASHCAST_STUCK_TIMEOUT_MINUTES', '30'))

# The worker writes a heartbeat file every minute. If it is older than this, the UI
# reports "worker not running" instead of guessing from how long an item has waited.
STASHCAST_WORKER_HEARTBEAT_STALE_SECONDS = int(
    os.environ.get('STASHCAST_WORKER_HEARTBEAT_STALE_SECONDS', '180')
)

# Ensure media directories exist
os.makedirs(STASHCAST_MEDIA_DIR, exist_ok=True)

# Media files configuration
# Served (and uploaded files linked) under /media/files/ to match the dev static
# route below and build_media_url(); overridable via STASHCAST_MEDIA_BASE_URL (CDN).
MEDIA_URL = '/media/files/'
MEDIA_ROOT = STASHCAST_MEDIA_DIR

# Huey configuration (SQLite backend)

HUEY = {
    'huey_class': 'huey.SqliteHuey',
    'name': 'stashcast',
    'filename': str(STASHCAST_DATA_DIR / 'huey.db'),
    'immediate': 'test' in sys.argv
    or 'pytest' in sys.modules,  # Execute tasks immediately during tests
    'consumer': {
        'workers': 2,
        'worker_type': 'thread',
    },
}