# Generated by Django 6.1 on 2026-08-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_mediagroup_youtube_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='download_attempts',
            field=models.PositiveIntegerField(default=0, help_text='How many times a download has been attempted for this item.'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Earliest time the paced queue may pick this item up (retry backoff).', null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PREFETCHING', 'Prefetching'), ('DOWNLOADING', 'Downloading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error'), ('ARCHIVED', 'Archived')], db_index=True, default='PREFETCHING', max_length=20),
        ),
    ]
