# Generated by Django 6.1 on 2026-08-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_mediaitem_download_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagroup',
            name='download_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', help_text='What to download for this group. Applies to the YouTube channel sync and to anything added to this group without an explicit type of its own.', max_length=10),
        ),
    ]
