# Generated by Django 6.1.1 on 2026-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_mediagroup_download_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='duration_checked_at',
            field=models.DateTimeField(blank=True, help_text='When the file duration was last measured.', null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='file_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Duration measured in the downloaded file, filled in by ./manage.py check_durations.', null=True),
        ),
    ]
