# Generated by Django 6.1.1 on 2026-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_mediaitem_duration_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='transcript',
            field=models.TextField(blank=True, help_text='Transcript produced by the speech-to-text server.'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='transcript_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='transcript_path',
            field=models.CharField(blank=True, help_text='WebVTT transcript file inside the item directory.', max_length=500),
        ),
    ]
