# Generated by Django 6.1.1 on 2026-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_mediaitem_transcript_mediaitem_transcript_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='transcript_error',
            field=models.TextField(blank=True, help_text='Why the last transcription attempt failed.'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='transcript_status',
            field=models.CharField(blank=True, choices=[('QUEUED', 'Waiting'), ('RUNNING', 'Transcribing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, help_text='Where this item is in the transcription process.', max_length=10),
        ),
    ]
