# Generated by Django 6.1.1 on 2026-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_mediaitem_transcript_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagroup',
            name='transcribe_new_downloads',
            field=models.BooleanField(default=False, help_text='Transcribe every new download in this group automatically. Requires STASHCAST_WHISPER_ENABLED; existing items are untouched - use the "Create transcript" action for those.'),
        ),
    ]
