# Generated by Django 6.1.1 on 2026-09-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_mediagroup_transcribe_new_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagroup',
            name='transcript_in_description',
            field=models.BooleanField(default=False, help_text='Also publish the transcript inside each episode description, as plain text without cue timings. For apps that ignore the transcript file - Apple Podcasts among them. Worth it for short episodes; a 60 minute one turns the description into a wall of text.'),
        ),
    ]
